### ISSUE TITLE
Better describe relationship to original/upstream Newlib and AVR Libc sources

### ISSUE THREAD

**Issue by tschwinge** [keith-packard/picolibc#18]
Can you please better describe (in the top-level 'README.md' file?) the relationship of picolibc to the original/upstream Newlib and AVR Libc sources?  That is, is picolibc a one-off fork, or do you intend to regularly merge (any/all?) changes from the upstream sources -- or something in between?

Depending on that, should the imported files be left unmodified as much as feasible, to make such future merges easy?

**Comment by keith-packard** [comment]
I've added a section in README.md that outlines what I've been doing so far, which is to try and keep picolibc code from newlib in sync with the newlib project.
