### ISSUE TITLE
picolibc build.md documentation needs to be updated with correct info (doc -> build.md)

### ISSUE THREAD

**Issue by jedxops** [keith-packard/picolibc#20]
The file is located at the following directory from this github repo
    doc/build.md
Please see the following screenshot:

![image](https://user-images.githubusercontent.com/26662692/69363040-8b252c00-0c44-11ea-8e75-d26d309710bc.png)

The cross-riscv64-unknown-elf.txt file should have values encapsulated by the ''
And it should be using 64 bit values, not 32. So all the 32's need to be replaced with 64.
Also, the filename itself is wrong, should be `cross-riscv64-unknown-elf.txt`

Please fix to avoid a mountain of confusion from readers.

**Comment by keith-packard** [comment]
Thanks! All fixed on master.

**Comment by jedxops** [comment]
> Thanks! All fixed on master.
Doesnt look fixed to me, I am on master branch. Nothing is different!

**Comment by jedxops** [comment]
much better thanks!
