### ISSUE TITLE
__aeabi_read_tp: LDC2 (or LLVM?) wants to use different places for return value

### ISSUE THREAD

**Issue by denizzzka** [keith-packard/picolibc#42]
For [this](https://github.com/keith-packard/picolibc/blob/38236f58d32d7be47882944967e146f59f03f4d9/newlib/libc/picolib/machine/arm/tls.c#L52) function:
```C
void *
__attribute__((naked))
__aeabi_read_tp(void)
{
	/* Load the address of __tls */
	asm("ldr r0,1f");
	/* Dereference to get the value of __tls */
	asm("ldr r0,[r0]");
	/* All done, return to caller */
	asm("bx lr");
	/* Holds the address of __tls */
	asm(".align 2");
	asm("1: .word __tls");
}
```

<s>Clang</s> ldc2 (LLVM-based Dlang compiler) with "-O0" option wants to get result value from stack instead of r0 register. If "-O3" or "-Oz" is used compiled code wants to obtain result by another different ways (`ldrb     r0, [r0, r1]`), but also not gets it from r0. As result of attempt to use this function binary obtains wrong value if compiled with <s>Clang</s> ldc2.

It is possible to use in this function some "clobber" or something else to point where is result placed for compiler?

**Comment by denizzzka** [comment]
Perhaps this is not a bug and I should write my own such function? But this call is hardcoded into ldc2, and also binary can be compiled from C and D sources both, and both of them need to call this function.

**Comment by keith-packard** [comment]
No, definitely a picolibc bug. I've moved the function to a .S file instead of attempting to have the C compiler generate the code we want. I'll push that out once some (unrelated) tests are complete. Thanks for the bug report!

**Comment by denizzzka** [comment]
Ok, thanks

I temporary changed my copy of tls.c by this way and it works:
```C
/* This needs to be global so that __aeabi_read_tp can
 * refer to it in an asm statement
 */
size_t *__tls;

/*
 * This cannot be a C ABI function as the compiler assumes that it
 * does not modify anything other than r0 and lr. So we create a
 * 'naked' function that respects those limitations.
 */
void *
__aeabi_read_tp(void)
{
	return (void*) *__tls;
}

/* The size of the thread control block.
 * TLS relocations are generated relative to
 * a location this far *before* the first thread
 * variable (!)
 */
#define TCB_SIZE	8

void
_set_tls(void *tls)
{
	__tls = (size_t *) tls - TCB_SIZE;
}

```

**Comment by keith-packard** [comment]
Yeah, that might well work with clang. With GCC, at -Os optimization, it used another register and broke code calling it.

In any case, I've pushed out a version written in assembly, so that should work on clang as well as it does with gcc.

**Comment by denizzzka** [comment]
> I've pushed out a version written in assembly, so that should work on clang as well as it does with gcc

I tested it with `ldc2` (not clang!) without succes: it generates same code as previous version: __aeabi_read_tp puts result into r0, and then tries to get result from stack:

![image](https://user-images.githubusercontent.com/974632/83324816-03267b80-a292-11ea-9a30-3c576de42e0c.png)

**Comment by denizzzka** [comment]
>  I've pushed out a version written in assembly, so that should work on clang as well as it does with gcc.

I tried this commit without success, it fails with same symptoms.

Clang compiles C version of __aeabi_read_tp (posted previously):
```C
void * __aeabi_read_tp(void)
{
	return (void*) *__tls;
}
```
into:
![image](https://user-images.githubusercontent.com/974632/83325507-e2145980-a296-11ea-90c9-54d35391ac41.png)

Generated by LLVM caller code is equal for my and your versions of __aeabi_read_tp:
![image](https://user-images.githubusercontent.com/974632/83325543-2dc70300-a297-11ea-93c4-3b9d36b3ba6b.png)

And it works with C version, but not with asm version.

**Comment by denizzzka** [comment]
I forgot to call _set_tls before use __aeabi_read_tp.
I am not sure, but may be this causes this problem, not asm issues.
I will reopen this issue afterch additional check.

**Comment by denizzzka** [comment]
Current variant tested and it works ok.
Problem was in https://github.com/keith-packard/picolibc/issues/45 and GC configuration on my side.
