### ISSUE TITLE
_set_tls: proposal to remove TCB_SIZE

### ISSUE THREAD

**Issue by denizzzka** [keith-packard/picolibc#46]
File `newlib/libc/picolib/machine/arm/tls.c` contains line:
```C
__tls = (uint8_t *) tls - TCB_SIZE;
```
What about remove of TCB_SIZE?

Rationale:
* neighboring `riscv/tls.c` is not contains such constant
* TCB can be different sized on different OSes

This is not very important, I always can add desired value when calling, but nonetheless.

**Comment by denizzzka** [comment]
Oh, I didn’t figure it out, this is a hardware feature! Incorrect issue, closing

**Comment by denizzzka** [comment]
In fact, I did not understand how this works! :-)
If I remove this `- TCB_SIZE` then my program fails at some point.

**Comment by keith-packard** [comment]
Yeah, GCC has a built-in notion of this value, which makes it effectively a part of the ABI.

**Comment by denizzzka** [comment]
Oh! I am on Clang - looks like LLVM have same built-in!

Thanks!
