### ISSUE TITLE
document meson and ninja dependency

### ISSUE THREAD

**Issue by ThomasHornschuh** [keith-packard/picolibc#48]
I did not find any hint about the required version of ninja and meson. I'm still using quite an old Ubuntu 16.04 LTS on one of my RISC-V development VMs, the version of ninja and meson provided by apt are really outdated.

Installing meson with sudo pip3 install meson gives 0.54.2 currently, this seems new enough.
I built ninja from sources.

At least some hints to the required versions should be added to the readme.

**Comment by keith-packard** [comment]
That's a great suggestion. I've added a couple of paragraphs to the top of the doc/build.md document describing the version requirements and providing some hints about how to get new enough bits.

**Comment by ThomasHornschuh** [comment]
Wow, that was fast :-)

**Comment by keith-packard** [comment]
You're most welcome!
