### ISSUE TITLE
Get rid of GPL'd printf tests

### ISSUE THREAD

**Issue by jserv** [keith-packard/picolibc#6]
The `printf` test suite might be the only source licensed under GNU GPL. Why not adopting other test cases without GPL? The [test suite](https://github.com/mpaland/printf/tree/master/test) from [mpaland/printf](https://github.com/mpaland/printf) looks pretty well and it is MIT licensed.

**Comment by keith-packard** [comment]
I'm fine with GPL code included as part of the test suite; that isn't delivered in applications and hence has no effect on overall target licensing. The printf test suite I included was gathered from a huge range of existing test suites and covers a nice array of corner cases, so I'd like to keep it around.

**Comment by joshtriplett** [comment]
@keith-packard That seems inconsistent with the licensing information in the README, which says that "none of the GPL-related bits are left in the repository". (I'm fine with GPLed code too, but the README should match the current status.)

**Comment by keith-packard** [comment]
Good point. I'll update the README to reflect the status of the printf tests

**Comment by keith-packard** [comment]
COPYING.picolibc now reflects all of the licenses in use, README.md notes that there are some tests under the GPL which do not end up in the library.
