### ISSUE TITLE
Possible naming issue

### ISSUE THREAD

**Issue by tarnh** [keith-packard/picolibc#7]
I've had filed an issue (https://github.com/keith-packard/picolibc/issues/1) referring to https://github.com/mtottenh/picolibc

Now I had to find out that my issue was censored by Github. Is it still possible for this repo's owner to get my issue's content?

**Comment by johandc** [comment]
That is unfortunate with the names.
And i cannot see the issue you are referring to.

**Comment by keith-packard** [comment]
I saw that other project before accepting the picolibc name for my version. It looked like the owner spent a couple of days messing around and having fun, but hasn't spent any time since then. That was four years ago.
